[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ecoscape-layers"
version = "0.0.7"
authors = [
]
description = "EcoScape habitat and matrix layer creation"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["ecoscape_layers"]

[project.scripts]
ecoscape-layers = "ecoscape_layers.main:cli"
